### PR TITLE
PMM-7106 Migrate to Go modules

### PR DESCRIPTION
**Pull request by ericyan**
https://jira.percona.com/browse/PMM-7106

As of 2020, [Dep is deprecated and archived](https://github.com/golang/dep) in favor of Go modules, which have had official support since Go 1.11.

Also updated dependencies.

### CODE REVIEW

**Comment by ericyan** [comment]
Any chance we can get this merged? @askomorokhov @AlekSi

**Comment by denisok** [comment]
@ericyan yes, we should be able to review and merge it soon

**Comment by Dasio** [comment]
https://jira.percona.com/browse/PMM-7725
We decided to remove also vendor folder, so please remove it.

**Review by percona-csalguero — CHANGES_REQUESTED** [review]
Could you please also remove the vendor directory?
Sorry for this late request. I just iupdated the Epic https://jira.percona.com/browse/PMM-7106 with a smart list like we have in https://jira.percona.com/browse/PMM-7662

**Comment by JiriCtvrtka** [comment]
PR with deleted vendors here: https://github.com/percona/proxysql_exporter/pull/48

**Pull request closed without merging**
