### PR TITLE
Collect from runtime_mysql_servers

### PR DESCRIPTION
**Pull request by weastur**
- [ ] https://github.com/Percona-Lab/pmm-submodules/pull/1770

PR add collector for runtime_mysql_servers. Don't work from stats user, so disabled by default. 

According to discussion https://github.com/sysown/proxysql/issues/1817 `runtime_mysql_servers` is the only place where you can find the current _status_ of the server, not the historical data like in `stats_mysql_connection_pool`. The issue with `stats_mysql_connection_pool` is that is too difficult to make an alert based on this data. For example, you can have a server both in the `OFFLINE_HARD` and the `ONLINE` state. 

On the other hand, `runtime_` tables, which are part of the `main` schema are not accessible under `stats` user, so I disabled this collector by default and leave a comment on README.md and tool usage message. 

Related issues about add ability for `stats` user read from some info from `main`:
https://github.com/sysown/proxysql/issues/2858
https://github.com/sysown/proxysql/issues/1661

### CODE REVIEW

**Comment by percona-csalguero** [comment]
```
217 total assertions

--- PASS: TestExporter (0.10s)
PASS
coverage: 76.3% of statements
ok      github.com/percona/proxysql_exporter    0.159s  coverage: 76.3% of statements
```

**Review by percona-csalguero — APPROVED** [review]

**Comment by weastur** [comment]
Hello! Is there any update?

**Comment by denisok** [comment]
@askomorokhov what needs to be done here?

**Comment by adivinho** [comment]
Original commits have been cherry-picked into other PR
https://github.com/percona/proxysql_exporter/pull/54

**Pull request closed without merging**
